apiVersion: hobbyfarm.io/v1
kind: Scenario
metadata:
  name: s-asfsafsafadfsadf
spec:
  id: s-asfsafsafadfsadf
  name: "How to not be bad"
  description: "in 5 easy steps, we will teach you how to not be bad"
  steps:
    - title: "step 1: live anywhere but where bad people live"
      content: "you should not live in bad land navigate to https://{{rancher-public-hostname}}"
    - title: "step 2: other things"
      content: "you shouasdfasdfe in bad land"
    - title: "step 3: asdfr things"
      content: "you shouasdfd"
  virtualmachines:
    - rancher: ubuntu1804-docker1
      node01: ubuntu1804-docker1
