apiVersion: hobbyfarm.io/v1
kind: Environment
metadata:
  name: e-asdfsafa
spec:
  display_name: "Example Environment"
  dnssuffix: example.hobbyfarm.io
  provider: ranchervm
  template_mapping:
    ubuntu1604-docker1:
      image: vm-ubuntu-1604-final
      module: provision-rvm
      executor_image: "oats87/terraform-controller-executor:latest"
  environment_specifics:
    endpoint: "http://rvm.fremont.rancherlabs.com"
  ip_translation_map:
    172.17.2: "184.105.214"
status:
  capacity:
    cpu: 64
    memory: 131072
    storage: 256
