apiVersion: hobbyfarm.io/v1
kind: VirtualMachineClaim
metadata:
  name: vmc-xxxxxyyyyz
spec:
  id: vmc-xxxxxyyyyz
  user: u-rr53u4n2uj
  vm:
    rancher:
      vm_id:
      template: ubuntu1804-docker1
    node01:
      vm_id:
      template: ubuntu1804-docker1
  vm_class_id: vmclass-sdfasdfa
status:
  bound: false
  ready: false